version: "3.9"

services:
  app:
    container_name: gopi-dev
    image: gopi-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - ${ADDRESS}:${ADDRESS}
    env_file: 
      - .env

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - dev-data:/var/lib/postgresql/data
    env_file: 
      - .env

volumes:
  dev-data:
