basePath: /api/v1/
definitions:
  models.Board:
    properties:
      created_at:
        example: 2024-01-22 17:03:50.283466+00
        type: string
      description:
        example: Board description
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Title
        type: string
      unique_id:
        example: 926e7309-12e4-4c50-824c-33737fb45f8a
        type: string
    type: object
  models.CreateBoardRequest:
    properties:
      description:
        example: My description
        type: string
      title:
        example: My title
        type: string
    type: object
  models.CreateBoardResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.HelloResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.RegisterRequest:
    properties:
      email:
        example: email@email.com
        type: string
      password:
        example: Password123&
        type: string
    type: object
  models.RegisterResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        example: 2024-01-22 17:03:50.283466+00
        type: string
      email:
        example: email@email.com
        type: string
      first_name:
        example: FirstName
        type: string
      id:
        example: 1
        type: integer
      last_name:
        example: LastName
        type: string
      password:
        example: hash
        type: string
      role:
        example: Tester
        type: string
      unique_id:
        example: 926e7309-12e4-4c50-824c-33737fb45f8a
        type: string
    type: object
host: localhost:4000
info:
  contact:
    email: tomasboda.dev@gmail.com
    name: Tomáš Boďa
    url: https://github.com/dvandyy
  description: REST api
  title: Gopi API
  version: "1.0"
paths:
  /:
    get:
      description: Retun a hello message if everything is ok
      produces:
      - application/json
      responses:
        "200":
          description: Return 'Hello from gopi!'
          schema:
            $ref: '#/definitions/models.HelloResponse'
      summary: Show a hello message
      tags:
      - Welcome
  /boards/{uid}:
    get:
      description: Return board with unique id
      parameters:
      - description: Board unique ID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Board'
      summary: Get board with UUID
      tags:
      - Boards
  /boards/new:
    post:
      description: Create a new board in database.
      parameters:
      - description: Create board with Title and Description
        in: body
        name: CreateBoardRequest
        required: true
        schema:
          $ref: '#/definitions/models.CreateBoardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateBoardResponse'
      summary: Create new board
      tags:
      - Boards
  /users/{uid}:
    get:
      description: Return user with unique id
      parameters:
      - description: User unique ID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get user with UUID
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: Create new user in database
      parameters:
      - description: Create user with Email and Password.
        in: body
        name: RegisterRequest
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.RegisterResponse'
      summary: Create new user
      tags:
      - Users
swagger: "2.0"
